"""Self-contained HTML report generator for FLORA analysis runs.

FLORAReport collects Plotly figures, metric tables, and text sections
and renders them into a single auto-contained HTML file that requires
no external dependencies to open.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import polars as pl
from jinja2 import Environment, BaseLoader

logger = logging.getLogger("flora.reports")

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #f8f9fa; margin: 0; padding: 0; }
  header { background: #1a6b3c; color: white; padding: 24px 40px; }
  header h1 { margin: 0; font-size: 2em; }
  header p { margin: 4px 0 0; opacity: 0.85; }
  .container { max-width: 1200px; margin: 0 auto; padding: 32px 24px; }
  .section { background: white; border-radius: 8px; padding: 24px; margin-bottom: 28px;
             box-shadow: 0 1px 4px rgba(0,0,0,0.08); }
  .section h2 { margin-top: 0; color: #1a6b3c; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }
  .metrics-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 16px; }
  .metric-card { background: #f0f7f3; border-radius: 6px; padding: 16px; text-align: center; }
  .metric-card .value { font-size: 2em; font-weight: bold; color: #1a6b3c; }
  .metric-card .label { color: #666; font-size: 0.9em; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9em; }
  th { background: #1a6b3c; color: white; padding: 10px 14px; text-align: left; }
  td { padding: 8px 14px; border-bottom: 1px solid #eee; }
  tr:hover td { background: #f0f7f3; }
  .text-block { color: #333; line-height: 1.6; white-space: pre-wrap; font-family: monospace;
                background: #f5f5f5; padding: 12px; border-radius: 4px; }
  footer { text-align: center; color: #888; padding: 24px; font-size: 0.85em; }
  .plotly-chart { width: 100%; }
</style>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
<header>
  <h1>{{ title }}</h1>
  <p>Generated {{ timestamp }} | FLORA v{{ version }}</p>
</header>
<div class="container">

{% for section in sections %}
<div class="section" id="{{ section.id }}">
  <h2>{{ section.title }}</h2>

  {% if section.type == "metrics" %}
  <div class="metrics-grid">
    {% for k, v in section.data.items() %}
    <div class="metric-card">
      <div class="value">{{ v }}</div>
      <div class="label">{{ k }}</div>
    </div>
    {% endfor %}
  </div>

  {% elif section.type == "table" %}
  <table>
    <thead><tr>{% for col in section.columns %}<th>{{ col }}</th>{% endfor %}</tr></thead>
    <tbody>
      {% for row in section.rows %}
      <tr>{% for cell in row %}<td>{{ cell }}</td>{% endfor %}</tr>
      {% endfor %}
    </tbody>
  </table>

  {% elif section.type == "text" %}
  <div class="text-block">{{ section.data }}</div>

  {% elif section.type == "plot" %}
  <div class="plotly-chart" id="{{ section.id }}_chart"></div>
  <script>
    var spec = {{ section.data }};
    Plotly.newPlot('{{ section.id }}_chart', spec.data, spec.layout, {responsive: true});
  </script>

  {% endif %}
</div>
{% endfor %}

</div>
<footer>
  Generated by FLORA — Feature Learning and Omics Research Analytics
</footer>
</body>
</html>
"""


@dataclass
class ReportSection:
    """A single section in the FLORA HTML report.

    Parameters
    ----------
    title : str
        Section heading.
    section_type : str
        One of: ``"metrics"``, ``"table"``, ``"text"``, ``"plot"``.
    data : Any
        Content appropriate for the section type.
    section_id : str, optional
        HTML element ID. Auto-generated if not provided.
    """

    title: str
    section_type: str
    data: Any
    section_id: str = ""
    columns: list[str] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.section_id:
            self.section_id = self.title.lower().replace(" ", "_").replace("/", "_")


class FLORAReport:
    """Consolidated HTML report for a FLORA analysis run.

    Parameters
    ----------
    title : str
        Report title displayed in the header.
    version : str
        Library version string.

    Examples
    --------
    >>> report = FLORAReport(title="Amazonian Microbiome Analysis")
    >>> report.add_metrics("Pipeline Summary", {"Samples": 80, "ASVs": 3421})
    >>> report.add_plot("PCoA", pcoa_fig)
    >>> report.save("results/report.html")
    """

    def __init__(
        self,
        title: str = "FLORA Analysis Report",
        version: str = "0.1.0",
    ) -> None:
        self.title = title
        self.version = version
        self._sections: list[ReportSection] = []

    def add_metrics(
        self,
        title: str,
        metrics: dict[str, Any],
        section_id: str = "",
    ) -> "FLORAReport":
        """Add a metrics card grid section.

        Parameters
        ----------
        title : str
            Section heading.
        metrics : dict
            Keys are metric labels, values are formatted values.
        section_id : str, optional
            HTML element ID.

        Returns
        -------
        FLORAReport
            Self, for method chaining.
        """
        formatted = {k: self._fmt(v) for k, v in metrics.items()}
        self._sections.append(ReportSection(
            title=title,
            section_type="metrics",
            data=formatted,
            section_id=section_id,
        ))
        return self

    def add_table(
        self,
        title: str,
        df: pl.DataFrame,
        max_rows: int = 50,
        section_id: str = "",
    ) -> "FLORAReport":
        """Add a data table section from a Polars DataFrame.

        Parameters
        ----------
        title : str
            Section heading.
        df : polars.DataFrame
            Table data. Columns become headers; rows become cells.
        max_rows : int
            Maximum rows to display in the report.
        section_id : str, optional
            HTML element ID.

        Returns
        -------
        FLORAReport
            Self, for method chaining.
        """
        sub = df.head(max_rows)
        cols = sub.columns
        rows = [[self._fmt(v) for v in row] for row in sub.iter_rows()]
        section = ReportSection(
            title=title,
            section_type="table",
            data=None,
            section_id=section_id,
        )
        section.columns = cols
        section.rows = rows
        self._sections.append(section)
        return self

    def add_plot(
        self,
        title: str,
        fig: Any,
        section_id: str = "",
    ) -> "FLORAReport":
        """Add a Plotly figure as an interactive plot section.

        Parameters
        ----------
        title : str
            Section heading.
        fig : plotly.graph_objects.Figure
            Any Plotly figure.
        section_id : str, optional
            HTML element ID.

        Returns
        -------
        FLORAReport
            Self, for method chaining.
        """
        json_str = fig.to_json()
        self._sections.append(ReportSection(
            title=title,
            section_type="plot",
            data=json_str,
            section_id=section_id,
        ))
        return self

    def add_text(
        self,
        title: str,
        text: str,
        section_id: str = "",
    ) -> "FLORAReport":
        """Add a preformatted text block section.

        Parameters
        ----------
        title : str
            Section heading.
        text : str
            Preformatted text (e.g. classification report, notes).
        section_id : str, optional
            HTML element ID.

        Returns
        -------
        FLORAReport
            Self, for method chaining.
        """
        self._sections.append(ReportSection(
            title=title,
            section_type="text",
            data=text,
            section_id=section_id,
        ))
        return self

    def save(self, path: str | Path) -> Path:
        """Render and save the report to an HTML file.

        The output file is fully self-contained (Plotly loaded from CDN).

        Parameters
        ----------
        path : str or Path
            Destination file path.

        Returns
        -------
        Path
            Resolved path to the saved report.
        """
        from datetime import datetime

        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)

        env = Environment(loader=BaseLoader())
        tmpl = env.from_string(_TEMPLATE)

        section_dicts = []
        for s in self._sections:
            d = {
                "id": s.section_id or s.title.lower().replace(" ", "_"),
                "title": s.title,
                "type": s.section_type,
                "data": s.data,
                "columns": s.columns,
                "rows": s.rows,
            }
            section_dicts.append(d)

        html = tmpl.render(
            title=self.title,
            version=self.version,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            sections=section_dicts,
        )

        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(html)

        logger.info("Report saved to %s (%d sections)", dest, len(self._sections))
        return dest

    @staticmethod
    def _fmt(value: Any) -> str:
        if isinstance(value, float):
            return f"{value:.4f}"
        if isinstance(value, int):
            return f"{value:,}"
        return str(value)
