"""FLORA Angular frontend static assets.

This package contains the pre-built Angular SPA served by the FLORA web
interface. The ``dist/`` subdirectory holds the production build output
generated by ``npm run build`` in the Angular project root.

To rebuild the frontend after making changes::

    ./scripts/build_frontend.sh
"""

from __future__ import annotations

from pathlib import Path


def get_dist_dir() -> Path:
    """Return the path to the built frontend assets directory.

    Returns ``None`` if the frontend has not been built yet.
    """
    dist = Path(__file__).parent / "dist"
    if dist.is_dir() and any(dist.iterdir()):
        return dist
    return None
